export const GIST_REQUEST = 'GIST_REQUEST';
export const GIST_REQUEST_SUCCESS = 'GIST_REQUEST_SUCCESS';
export const GIST_REQUEST_ERROR = 'GIST_REQUEST_ERROR';

export const GIST_COMMENTS_REQUEST = 'GIST_COMMENTS_REQUEST';
export const GIST_COMMENTS_REQUEST_SUCCESS = 'GIST_COMMENTS_REQUEST_SUCCESS';
export const GIST_COMMENTS_REQUEST_ERROR = 'GIST_COMMENTS_REQUEST_ERROR';

export const SEND_COMMENT_REQUEST = 'SEND_COMMENT_REQUEST';
export const SEND_COMMENT_REQUEST_SUCCESS = 'SEND_COMMENT_REQUEST_SUCCESS';
export const SEND_COMMENT_REQUEST_ERROR = 'SEND_COMMENT_REQUEST_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';
export const IS_LOGGED = 'IS_LOGGED';
export const LOGOUT = 'LOGOUT';

// Spinner
export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'
